project_name: xixuanyunsign

builds:
  - id: windows_386
    goos:
      - windows
    goarch:
      - 386
    main: ./main.go  # 你的入口文件路径
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-L/c/msys64/mingw32/lib  # 设置MinGW库路径
      - CGO_CFLAGS=-I/c/msys64/mingw32/include  # 设置MinGW头文件路径
    ldflags: "-s -w -extldflags '-static'"  # 使编译静态化
    goarm: [7]


