version: 2
builds:
  # Linux amd64
  - id: linux-amd64
    main: ./
    binary: xixunyunsign
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/amd64
      - PKG_CONFIG_PATH=/sysroot/linux/amd64/usr/lib/pkgconfig:/sysroot/linux/amd64/usr/local/lib/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Linux arm64
  - id: linux-arm64
    main: ./
    binary: xixunyunsign
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/arm64
      - PKG_CONFIG_PATH=/sysroot/linux/arm64/usr/lib/pkgconfig:/sysroot/linux/arm64/usr/local/lib/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Linux armhf (armv7)
  - id: linux-armhf
    main: ./
    binary: xixunyunsign
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
      - CGO_CFLAGS=--sysroot=/sysroot/linux/armhf
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/armhf
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/armhf
      - PKG_CONFIG_PATH=/sysroot/linux/armhf/opt/vc/lib/pkgconfig:/sysroot/linux/armhf/usr/lib/arm-linux-gnueabihf/pkgconfig:/sysroot/linux/armhf/usr/lib/pkgconfig:/sysroot/linux/armhf/usr/local/lib/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Linux armv5
  - id: linux-armv5
    main: ./
    binary: xixunyunsign
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 5
    env:
      - CGO_ENABLED=1
      - GOARM=5
      - CC=arm-linux-gnueabi-gcc # 使用适合 ARMv5 的 GCC 编译器
      - CXX=arm-linux-gnueabi-g++ # 使用适合 ARMv5 的 C++ 编译器
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Linux armv5 静态编译
  - id: linux-armv5-static
    main: ./
    binary: xixunyunsign
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 5
    env:
      - CGO_ENABLED=1
      - GOARM=5
      - CC=arm-linux-gnueabi-gcc # 使用适合 ARMv5 的 GCC 编译器
      - CXX=arm-linux-gnueabi-g++ # 使用适合 ARMv5 的 C++ 编译器
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Windows amd64
  - id: windows-amd64
    main: ./
    binary: xixunyunsign.exe
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/windows/amd64
      - PKG_CONFIG_PATH=/sysroot/windows/amd64/usr/lib/pkgconfig:/sysroot/windows/amd64/usr/local/lib/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: golang-cross
    builds:
      - linux-amd64
      - linux-arm64
      - linux-armhf
      - linux-armv5
      - linux-armhf-static
      - linux-arm64-static
      - linux-armv5-static
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    wrap_in_directory: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: theshdowaura
    name: xixuanyunsign
  prerelease: auto
  draft: false
