version: 2

builds:
  # Linux amd64
  - id: linux-amd64-v1
    main: ./
    binary: xixunyunsign
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Linux arm64
  - id: linux-arm64-v1
    main: ./
    binary: xixunyunsign
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Linux armhf
  - id: linux-armhf-v1
    main: ./
    binary: xixunyunsign
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Linux armv5
  - id: linux-armv5-v1
    main: ./
    binary: xixunyunsign
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 5
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Linux armv5 Static
  - id: linux-armv5-static-v1
    main: ./
    binary: xixunyunsign
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 5
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: linux-amd64-archive-v1
    builds:
      - linux-amd64-v1
    name_template: "xixunyunsign_{{ .Version }}_linux_amd64.zip"
    format: zip

  - id: linux-arm64-archive-v1
    builds:
      - linux-arm64-v1
    name_template: "xixunyunsign_{{ .Version }}_linux_arm64.zip"
    format: zip

  - id: linux-armhf-archive-v1
    builds:
      - linux-armhf-v1
    name_template: "xixunyunsign_{{ .Version }}_linux_armhf.zip"
    format: zip

  - id: linux-armv5-archive-v1
    builds:
      - linux-armv5-v1
    name_template: "xixunyunsign_{{ .Version }}_linux_armv5.zip"
    format: zip

  - id: linux-armv5-static-archive-v1
    builds:
      - linux-armv5-static-v1
    name_template: "xixunyunsign_{{ .Version }}_linux_armv5_static.zip"
    format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

release:
  github:
    owner: theshdowaura
    name: xixuanyunsign
  prerelease: auto
  draft: false
