name: Release

on:
  workflow_dispatch: # 手动触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # 检出代码，获取完整的 Git 历史记录
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 设置 Go 版本（可选）
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22' # 根据您的需求调整版本

      # 安装依赖
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf

      # 验证交叉编译器
      - name: Verify Cross Compiler
        run: |
          which arm-linux-gnueabihf-gcc
          arm-linux-gnueabihf-gcc --version

      # 确保符号链接正确
      - name: Ensure Symlink for Cross Compiler
        run: |
          sudo ln -sf /usr/bin/arm-linux-gnueabihf-gcc-10 /usr/bin/arm-linux-gnueabihf-gcc

      # 运行 GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest # 安装最新版本的 GoReleaser
          args: release --clean # 移除 --debug 参数
          debug: true # 启用调试模式
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 设置特定架构的 C 编译器
          CC_LINUX_ARM_V7: arm-linux-gnueabihf-gcc
