name: Release

on:
  workflow_dispatch: # 手动触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # 检出代码，获取完整的 Git 历史记录
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 安装 Go（可选，根据项目需要）
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20' # 根据您的需求调整版本

      # 安装依赖
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf

      # 列出交叉编译器，验证安装
      - name: List Cross Compilers
        run: |
          ls -l /usr/bin/arm-linux-gnueabihf-gcc*
          arm-linux-gnueabihf-gcc --version || echo "arm-linux-gnueabihf-gcc not found"

      # 确保符号链接正确（根据实际编译器版本调整）
      - name: Ensure Symlink for Cross Compiler
        run: |
          sudo ln -sf /usr/bin/arm-linux-gnueabihf-gcc-12 /usr/bin/arm-linux-gnueabihf-gcc

      # 再次验证编译器
      - name: Verify Cross Compiler
        run: |
          which arm-linux-gnueabihf-gcc
          arm-linux-gnueabihf-gcc --version

      # 运行 GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CC_LINUX_ARM_V7: arm-linux-gnueabihf-gcc-12 # 根据实际编译器调整
