name: Release

on:
  workflow_dispatch: # 手动触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码，获取完整的 Git 历史记录
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. 设置 Go 版本为 1.22
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      # 3. 安装依赖，包括交叉编译器
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf

      # 4. 列出所有 ARM GCC 编译器以进行诊断
      - name: List ARM GCC Compilers
        run: |
          echo "Listing all arm-linux-gnueabihf-gcc* in /usr/bin:"
          ls -l /usr/bin/arm-linux-gnueabihf-gcc*
          echo "File details:"
          file /usr/bin/arm-linux-gnueabihf-gcc*

      # 5. 确保符号链接正确
      - name: Ensure Symlink for Cross Compiler
        run: |
          # 移除现有的符号链接（如果存在）
          sudo rm -f /usr/bin/arm-linux-gnueabihf-gcc
          # 查找实际的 gcc 版本，例如 arm-linux-gnueabihf-gcc-10 或 arm-linux-gnueabihf-gcc-12
          GCC_VERSION=$(ls /usr/bin/arm-linux-gnueabihf-gcc-* | head -n 1)
          # 创建新的符号链接指向实际的 gcc 版本
          sudo ln -s "$GCC_VERSION" /usr/bin/arm-linux-gnueabihf-gcc

      # 6. 再次验证编译器
      - name: Verify Symlink and Compiler
        run: |
          echo "Verifying the symlink and compiler:"
          ls -l /usr/bin/arm-linux-gnueabihf-gcc
          arm-linux-gnueabihf-gcc --version || echo "arm-linux-gnueabihf-gcc not found"

      # 7. 列出 Git 标签以确保正确
      - name: List Git Tags
        run: git tag

      # 8. 运行 GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest # 安装最新版本的 GoReleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 设置特定架构的 C 编译器
          CC_LINUX_ARM_V7: arm-linux-gnueabihf-gcc
